"""Generate manifest_candidates_expanded.jsonl with 76 new candidates across all 16 directions."""
from __future__ import annotations
import json
from datetime import UTC, datetime
from pathlib import Path

CANDIDATES = [
    # ===== 00: DL / CNN / NLP Foundation =====
    ("paper_041", "ImageNet Classification with Deep Convolutional Neural Networks", ["Alex Krizhevsky","Ilya Sutskever","Geoffrey Hinton"], 2012, "NeurIPS 2012", "https://papers.nips.cc/paper/2012/hash/c399862d3b9d6b76c8436e924a68c45b-Abstract.html", None, ["deep-learning","cnn","vision"], ["AlexNet","ImageNet","CNN"], "S", True, False, "CNN foundation; ImageNet breakthrough", "metadata_only"),
    ("paper_042", "Very Deep Convolutional Networks for Large-Scale Image Recognition", ["Karen Simonyan","Andrew Zisserman"], 2014, "ICLR 2015", "https://arxiv.org/abs/1409.1556", "1409.1556", ["deep-learning","cnn","vision"], ["VGG","deep-network"], "A", False, False, "Classical deep vision architecture", "overview_only"),
    ("paper_043", "Batch Normalization: Accelerating Deep Network Training by Reducing Internal Covariate Shift", ["Sergey Ioffe","Christian Szegedy"], 2015, "ICML 2015", "https://arxiv.org/abs/1502.03167", "1502.03167", ["deep-learning","training"], ["BatchNorm","normalization"], "S", True, False, "Training stability breakthrough", "full_pdf"),
    ("paper_044", "Deep Residual Learning for Image Recognition", ["Kaiming He","Xiangyu Zhang","Shaoqing Ren","Jian Sun"], 2015, "CVPR 2016", "https://arxiv.org/abs/1512.03385", "1512.03385", ["deep-learning","cnn","vision"], ["ResNet","residual-connection","skip-connection"], "S", True, False, "Residual learning foundation", "full_pdf"),
    ("paper_045", "Adam: A Method for Stochastic Optimization", ["Diederik P. Kingma","Jimmy Ba"], 2014, "ICLR 2015", "https://arxiv.org/abs/1412.6980", "1412.6980", ["deep-learning","optimization"], ["Adam","optimizer","stochastic-optimization"], "S", True, False, "Default optimizer for most DL", "full_pdf"),
    ("paper_046", "Dropout: A Simple Way to Prevent Neural Networks from Overfitting", ["Nitish Srivastava","Geoffrey Hinton","Alex Krizhevsky","Ilya Sutskever","Ruslan Salakhutdinov"], 2014, "JMLR 2014", "https://jmlr.org/papers/v15/srivastava14a.html", None, ["deep-learning","regularization"], ["Dropout","regularization"], "S", True, False, "Key regularization technique", "overview_only"),
    ("paper_047", "Sequence to Sequence Learning with Neural Networks", ["Ilya Sutskever","Oriol Vinyals","Quoc V. Le"], 2014, "NeurIPS 2014", "https://arxiv.org/abs/1409.3215", "1409.3215", ["deep-learning","nlp","sequence"], ["Seq2Seq","LSTM","machine-translation"], "S", True, False, "Sequence-to-sequence foundation", "full_pdf"),
    ("paper_048", "Neural Machine Translation by Jointly Learning to Align and Translate", ["Dzmitry Bahdanau","KyungHyun Cho","Yoshua Bengio"], 2014, "ICLR 2015", "https://arxiv.org/abs/1409.0473", "1409.0473", ["deep-learning","nlp","attention"], ["attention","NMT","encoder-decoder"], "S", True, False, "Attention mechanism origin", "full_pdf"),
    ("paper_049", "Attention Is All You Need", ["Ashish Vaswani","Noam Shazeer","Niki Parmar","Jakob Uszkoreit","Llion Jones","Aidan N. Gomez","Lukasz Kaiser","Illia Polosukhin"], 2017, "NeurIPS 2017", "https://arxiv.org/abs/1706.03762", "1706.03762", ["deep-learning","nlp","transformer","attention"], ["Transformer","self-attention","encoder-decoder"], "S", True, False, "Foundation of all modern LLMs", "full_pdf"),
    ("paper_050", "An Image is Worth 16x16 Words: Transformers for Image Recognition at Scale", ["Alexey Dosovitskiy","Lucas Beyer","Alexander Kolesnikov","Dirk Weissenborn","Xiaohua Zhai","Thomas Unterthiner","Mostafa Dehghani","Matthias Minderer","Georg Heigold","Sylvain Gelly","Jakob Uszkoreit","Neil Houlsby"], 2020, "ICLR 2021", "https://arxiv.org/abs/2010.11929", "2010.11929", ["deep-learning","vision","transformer"], ["ViT","vision-transformer","image-classification"], "S", True, False, "Vision transformer breakthrough", "full_pdf"),

    # ===== 00a: Transformer / LLM Base =====
    ("paper_051", "Improving Language Understanding by Generative Pre-Training (GPT)", ["Alec Radford","Karthik Narasimhan","Tim Salimans","Ilya Sutskever"], 2018, "OpenAI", "https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf", None, ["llm","transformer","nlp"], ["GPT","generative-pre-training","language-model"], "S", True, False, "First GPT; generative pre-training", "overview_only"),
    ("paper_052", "Language Models are Unsupervised Multitask Learners (GPT-2)", ["Alec Radford","Jeffrey Wu","Rewon Child","David Luan","Dario Amodei","Ilya Sutskever"], 2019, "OpenAI", "https://d4mucfpksywv.cloudfront.net/better-language-models/language_models_are_unsupervised_multitask_learners.pdf", None, ["llm","transformer","nlp"], ["GPT-2","zero-shot","scaling"], "S", True, False, "Scaling language models", "overview_only"),
    ("paper_053", "BERT: Pre-training of Deep Bidirectional Transformers for Language Understanding", ["Jacob Devlin","Ming-Wei Chang","Kenton Lee","Kristina Toutanova"], 2018, "NAACL 2019", "https://arxiv.org/abs/1810.04805", "1810.04805", ["llm","nlp","transformer"], ["BERT","bidirectional","masked-language-model","pre-training"], "S", True, False, "Bidirectional encoder; NLP revolution", "full_pdf"),
    ("paper_054", "Exploring the Limits of Transfer Learning with a Unified Text-to-Text Transformer (T5)", ["Colin Raffel","Noam Shazeer","Adam Roberts","Katherine Lee","Sharan Narang","Michael Matena","Yanqi Zhou","Wei Li","Peter J. Liu"], 2019, "JMLR 2020", "https://arxiv.org/abs/1910.10683", "1910.10683", ["llm","nlp","transformer"], ["T5","text-to-text","transfer-learning"], "S", True, False, "Unified text-to-text framework", "full_pdf"),
    ("paper_055", "Language Models are Few-Shot Learners (GPT-3)", ["Tom B. Brown","Benjamin Mann","Nick Ryder","Melanie Subbiah","Jared Kaplan","Prafulla Dhariwal","Arvind Neelakantan","Pranav Shyam","Girish Sastry","Amanda Askell","Sandhini Agarwal","Ariel Herbert-Voss","Gretchen Krueger","Tom Henighan","Rewon Child","Aditya Ramesh","Daniel M. Ziegler","Jeffrey Wu","Clemens Winter","Christopher Hesse","Mark Chen","Eric Sigler","Mateusz Litwin","Scott Gray","Benjamin Chess","Jack Clark","Christopher Berner","Sam McCandlish","Alec Radford","Ilya Sutskever","Dario Amodei"], 2020, "NeurIPS 2020", "https://arxiv.org/abs/2005.14165", "2005.14165", ["llm","nlp","few-shot"], ["GPT-3","few-shot-learning","in-context-learning","scaling"], "S", True, False, "Few-shot learning at scale", "full_pdf"),
    ("paper_056", "Scaling Laws for Neural Language Models", ["Jared Kaplan","Sam McCandlish","Tom Henighan","Tom B. Brown","Benjamin Chess","Rewon Child","Scott Gray","Alec Radford","Jeffrey Wu","Dario Amodei"], 2020, "arXiv", "https://arxiv.org/abs/2001.08361", "2001.08361", ["llm","scaling","nlp"], ["scaling-laws","compute-optimal","power-law"], "S", True, False, "Foundation of LLM scaling theory", "full_pdf"),
    ("paper_057", "Training Compute-Optimal Large Language Models (Chinchilla)", ["Jordan Hoffmann","Sebastian Borgeaud","Arthur Mensch","Elena Buchatskaya","Trevor Cai","Eliza Rutherford","Diego de Las Casas","Lisa Anne Hendricks","Johannes Welbl","Aidan Clark","Tom Hennigan","Eric Noland","Katie Millican","George van den Driessche","Bogdan Damoc","Aurelia Guy","Simon Osindero","Karen Simonyan","Erich Elsen","Jack W. Rae","Oriol Vinyals","Laurent Sifre"], 2022, "NeurIPS 2022", "https://arxiv.org/abs/2203.15556", "2203.15556", ["llm","scaling","nlp"], ["Chinchilla","compute-optimal","scaling-laws","data-scaling"], "S", True, False, "Optimal compute allocation", "full_pdf"),
    ("paper_058", "Training language models to follow instructions with human feedback (InstructGPT)", ["Long Ouyang","Jeff Wu","Xu Jiang","Diogo Almeida","Carroll L. Wainwright","Pamela Mishkin","Chong Zhang","Sandhini Agarwal","Katarina Slama","Alex Ray","John Schulman","Jacob Hilton","Fraser Kelton","Luke Miller","Maddie Simens","Amanda Askell","Peter Welinder","Paul Christiano","Jan Leike","Ryan Lowe"], 2022, "NeurIPS 2022", "https://arxiv.org/abs/2203.02155", "2203.02155", ["llm","alignment","rlhf"], ["RLHF","InstructGPT","instruction-following","alignment"], "S", True, False, "Alignment via RLHF", "full_pdf"),
    ("paper_059", "LLaMA: Open and Efficient Foundation Language Models", ["Hugo Touvron","Thibaut Lavril","Gautier Izacard","Xavier Martinet","Marie-Anne Lachaux","Timothee Lacroix","Baptiste Roziere","Naman Goyal","Eric Hambro","Faisal Azhar","Aurelien Rodriguez","Armand Joulin","Edouard Grave","Guillaume Lample"], 2023, "arXiv", "https://arxiv.org/abs/2302.13971", "2302.13971", ["llm","open-source","nlp"], ["LLaMA","open-source","efficient"], "S", True, False, "Open-source LLM family", "full_pdf"),
    ("paper_060", "Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity", ["William Fedus","Barret Zoph","Noam Shazeer"], 2021, "JMLR 2022", "https://arxiv.org/abs/2101.03961", "2101.03961", ["llm","moe","sparse"], ["MoE","Switch-Transformer","sparsity","mixture-of-experts"], "A", True, False, "Mixture of Experts at scale", "full_pdf"),
    ("paper_061", "Mixtral of Experts", ["Albert Q. Jiang","Alexandre Sablayrolles","Arthur Mensch","Chris Bamford","Devendra Singh Chaplot","Diego de las Casas","Florian Bressand","Gianna Lengyel","Guillaume Lample","Lucile Saulnier","Lelio Renard Lavaud","Marie-Anne Lachaux","Pierre Stock","Teven Le Scao","Thibaut Lavril","Thomas Wang","Timothee Lacroix","William El Sayed"], 2024, "arXiv", "https://arxiv.org/abs/2401.04088", "2401.04088", ["llm","moe","sparse"], ["Mixtral","sparse-MoE","open-source"], "A", False, False, "Sparse MoE open model", "full_pdf"),
    ("paper_062", "DeepSeek-V3 Technical Report", ["DeepSeek-AI"], 2024, "arXiv", "https://arxiv.org/abs/2412.19437", "2412.19437", ["llm","moe","frontier"], ["DeepSeek-V3","MoE","multi-token-prediction"], "A", False, True, "Frontier open LLM; MoE architecture", "full_pdf"),
    ("paper_063", "DeepSeek-R1: Incentivizing Reasoning Capability in LLMs via Reinforcement Learning", ["DeepSeek-AI"], 2025, "arXiv", "https://arxiv.org/abs/2501.12948", "2501.12948", ["llm","reasoning","rl"], ["DeepSeek-R1","chain-of-thought","RL","reasoning"], "A", False, True, "Reasoning via RL; GRPO", "full_pdf"),

    # ===== 02: Prompting / Reasoning =====
    ("paper_064", "Self-Consistency Improves Chain of Thought Reasoning in Language Models", ["Xuezhi Wang","Jason Wei","Dale Schuurmans","Quoc Le","Ed Chi","Sharan Narang","Aakanksha Chowdhery","Denny Zhou"], 2022, "ICLR 2023", "https://arxiv.org/abs/2203.11171", "2203.11171", ["reasoning","prompting"], ["self-consistency","chain-of-thought","majority-voting"], "S", True, False, "Improves CoT via sampling and voting", "full_pdf"),
    ("paper_065", "Least-to-Most Prompting Enables Complex Reasoning in Large Language Models", ["Denny Zhou","Nathanael Scharli","Le Hou","Jason Wei","Nathan Scales","Xuezhi Wang","Dale Schuurmans","Claire Cui","Olivier Bousquet","Quoc Le","Ed Chi"], 2022, "ICLR 2023", "https://arxiv.org/abs/2205.10625", "2205.10625", ["reasoning","prompting"], ["least-to-most","decomposition","complex-reasoning"], "S", True, False, "Hierarchical problem decomposition", "full_pdf"),
    ("paper_066", "PAL: Program-Aided Language Models", ["Luyu Gao","Aman Madaan","Shuyan Zhou","Uri Alon","Pengfei Liu","Yiming Yang","Jamie Callan","Graham Neubig"], 2022, "ICML 2023", "https://arxiv.org/abs/2211.10435", "2211.10435", ["reasoning","code-generation"], ["PAL","program-aided","code-as-reasoning"], "A", False, False, "Program-aided language reasoning", "full_pdf"),
    ("paper_067", "Program of Thoughts Prompting: Disentangling Computation from Reasoning for Numerical Reasoning Tasks", ["Wenhu Chen","Xueguang Ma","Xinyi Wang","William W. Cohen"], 2022, "TMLR 2023", "https://arxiv.org/abs/2211.12588", "2211.12588", ["reasoning","code-generation"], ["PoT","program-of-thoughts","numerical-reasoning"], "A", False, False, "Code as reasoning for math", "overview_only"),
    ("paper_068", "Graph of Thoughts: Solving Elaborate Problems with Large Language Models", ["Maciej Besta","Nils Blach","Ales Kubicek","Robert Gerstenberger","Michal Podstawski","Lukas Gianinazzi","Joanna Gajda","Tomasz Lehmann","Hubert Niewiadomski","Piotr Nyczyk","Torsten Hoefler"], 2023, "AAAI 2024", "https://arxiv.org/abs/2308.09687", "2308.09687", ["reasoning","prompting","graph"], ["GoT","graph-of-thoughts","graph-reasoning"], "A", False, False, "Graph-structured reasoning", "full_pdf"),
    ("paper_069", "Plan-and-Solve Prompting: Improving Zero-Shot Chain-of-Thought Reasoning by Large Language Models", ["Lei Wang","Wanyu Xu","Yihuai Lan","Zhiqiang Hu","Yunshi Lan","Roy Ka-Wei Lee","Ee-Peng Lim"], 2023, "ACL 2023", "https://arxiv.org/abs/2305.04091", "2305.04091", ["reasoning","prompting"], ["Plan-and-Solve","zero-shot-CoT","planning"], "A", False, False, "Zero-shot planning + reasoning", "overview_only"),
    ("paper_070", "Reflexion: Language Agents with Verbal Reinforcement Learning", ["Noah Shinn","Federico Cassano","Ashwin Gopinath","Karthik Narasimhan","Shunyu Yao"], 2023, "NeurIPS 2023", "https://arxiv.org/abs/2303.11366", "2303.11366", ["reasoning","reflection","rl"], ["Reflexion","verbal-RL","self-reflection","agent"], "S", True, False, "Verbal reinforcement learning for agents", "full_pdf"),

    # ===== 03: Retrieval / RAG Base =====
    ("paper_071", "REALM: Retrieval-Augmented Language Model Pre-Training", ["Kelvin Guu","Kenton Lee","Zora Tung","Panupong Pasupat","Ming-Wei Chang"], 2020, "ICML 2020", "https://arxiv.org/abs/2002.08909", "2002.08909", ["retrieval","rag","pre-training"], ["REALM","retrieval-augmented","knowledge-retrieval"], "S", True, False, "Retrieval-augmented pre-training", "full_pdf"),
    ("paper_072", "Dense Passage Retrieval for Open-Domain Question Answering", ["Vladimir Karpukhin","Barlas Oguz","Sewon Min","Patrick Lewis","Ledell Wu","Sergey Edunov","Danqi Chen","Wen-tau Yih"], 2020, "EMNLP 2020", "https://arxiv.org/abs/2004.04906", "2004.04906", ["retrieval","dense-retrieval","qa"], ["DPR","dense-passage-retrieval","dual-encoder"], "S", True, False, "Dense passage retrieval foundation", "full_pdf"),
    ("paper_073", "Leveraging Passage Retrieval with Generative Models for Open Domain Question Answering (FiD)", ["Gautier Izacard","Edouard Grave"], 2020, "EACL 2021", "https://arxiv.org/abs/2007.01282", "2007.01282", ["retrieval","rag","qa"], ["FiD","fusion-in-decoder","generative-qa"], "S", True, False, "Fusion-in-Decoder for RAG", "full_pdf"),
    ("paper_074", "ColBERT: Efficient and Effective Passage Search via Contextualized Late Interaction over BERT", ["Omar Khattab","Matei Zaharia"], 2020, "SIGIR 2020", "https://arxiv.org/abs/2004.12832", "2004.12832", ["retrieval","dense-retrieval","late-interaction"], ["ColBERT","late-interaction","contextualized-embedding"], "A", True, False, "Late interaction retrieval model", "full_pdf"),
    ("paper_075", "Unsupervised Dense Information Retrieval with Contrastive Learning (Contriever)", ["Gautier Izacard","Mathilde Caron","Lucas Hosseini","Sebastian Riedel","Piotr Bojanowski","Armand Joulin","Edouard Grave"], 2021, "TMLR 2022", "https://arxiv.org/abs/2112.09118", "2112.09118", ["retrieval","contrastive-learning"], ["Contriever","unsupervised","contrastive","dense-retrieval"], "A", False, False, "Unsupervised dense retrieval", "full_pdf"),
    ("paper_076", "Atlas: Few-shot Learning with Retrieval Augmented Models", ["Gautier Izacard","Patrick Lewis","Edouard Grave","Sebastian Riedel","Armand Joulin","Jason Weston"], 2022, "JMLR 2023", "https://arxiv.org/abs/2208.03299", "2208.03299", ["retrieval","few-shot","rag"], ["Atlas","few-shot","retrieval-augmented"], "A", False, False, "Few-shot retrieval-augmented LM", "overview_only"),
    ("paper_077", "Precise Zero-Shot Dense Retrieval without Relevance Labels (HyDE)", ["Luyu Gao","Xueguang Ma","Jimmy Lin","Jamie Callan"], 2022, "ACL 2023", "https://arxiv.org/abs/2212.10496", "2212.10496", ["retrieval","dense-retrieval","zero-shot"], ["HyDE","hypothetical-document","zero-shot"], "A", False, False, "Hypothetical document embeddings", "full_pdf"),
    ("paper_078", "RAPTOR: Recursive Abstractive Processing for Tree-Organized Retrieval", ["Parth Sarthi","Salman Abdullah","Aditi Tuli","Shubh Khanna","Rahul Gupta"], 2024, "ICLR 2024", "https://arxiv.org/abs/2401.18059", "2401.18059", ["retrieval","rag","summarization"], ["RAPTOR","recursive","tree-structure","abstractive"], "A", False, False, "Recursive summarization for retrieval", "full_pdf"),
    ("paper_079", "LightRAG: Simple and Fast Retrieval-Augmented Generation", ["Zirui Guo","Lianghao Xia","Zhao Li","Hongzhi Yin"], 2024, "arXiv", "https://arxiv.org/abs/2410.05779", "2410.05779", ["retrieval","rag","graph"], ["LightRAG","graph-RAG","lightweight"], "A", False, True, "Lightweight graph-based RAG", "full_pdf"),

    # ===== 04: Agentic RAG additions =====
    ("paper_080", "Active Retrieval Augmented Generation (FLARE)", ["Zhengbao Jiang","Frank F. Xu","Luyu Gao","Zhiqing Sun","Qian Liu","Jane Dwivedi-Yu","Yiming Yang","Jamie Callan","Graham Neubig"], 2023, "EMNLP 2023", "https://arxiv.org/abs/2305.06983", "2305.06983", ["agentic-rag","active-retrieval"], ["FLARE","active-retrieval","on-demand"], "S", True, False, "Active/iterative retrieval during generation", "full_pdf"),

    # ===== 06: Tool Use / Code Agent =====
    ("paper_081", "WebArena: A Realistic Web Environment for Building Autonomous Agents", ["Shuyan Zhou","Frank F. Xu","Hao Zhu","Xuhui Zhou","Robert Lo","Abishek Sridhar","Xianyi Cheng","Yonatan Bisk","Daniel Fried","Uri Alon","Graham Neubig"], 2023, "ICLR 2024", "https://arxiv.org/abs/2307.13854", "2307.13854", ["tool-use","web-agents","benchmark"], ["WebArena","web-environment","autonomous-agent"], "S", True, False, "Realistic web agent benchmark", "full_pdf"),
    ("paper_082", "SWE-bench: Can Language Models Resolve Real-World GitHub Issues?", ["Carlos E. Jimenez","John Yang","Alexander Wettig","Shunyu Yao","Kexin Pei","Ofir Press","Karthik Narasimhan"], 2023, "ICLR 2024", "https://arxiv.org/abs/2310.06770", "2310.06770", ["tool-use","code-agent","benchmark"], ["SWE-bench","software-engineering","GitHub"], "S", True, False, "Standard software engineering benchmark", "full_pdf"),
    ("paper_083", "ToolLLM: Facilitating Large Language Models to Master 16000+ Real-world APIs", ["Yujia Qin","Shihao Liang","Yining Ye","Kunlun Zhu","Lan Yan","Yaxi Lu","Yankai Lin","Xin Cong","Xiangru Tang","Bill Qian","Sihan Zhao","Laurent Hong","Rui Tian","RuoBing Xie","Jie Zhou","Mark Gerstein","Dahua Lin","Zhiyuan Liu","Maosong Sun"], 2023, "NeurIPS 2024", "https://arxiv.org/abs/2307.16789", "2307.16789", ["tool-use","api","llm"], ["ToolLLM","ToolBench","API-calling"], "A", True, False, "Large-scale tool learning", "full_pdf"),
    ("paper_084", "CodeAct: A Unified Code Model for Web Agents", ["Xingyao Wang","Yangyi Chen","Lifan Yuan","Yizhe Zhang","Yunzhu Li","Hao Peng","Heng Ji"], 2024, "arXiv", "https://arxiv.org/abs/2402.01030", "2402.01030", ["tool-use","code-agent","web-agent"], ["CodeAct","code-as-action","unified-agent"], "A", False, False, "Code as universal action space", "full_pdf"),
    ("paper_085", "OSWorld: Benchmarking Multimodal Agents for Open-Ended Tasks in Real Computer Environments", ["Tianbao Xie","Danyang Zhang","Jixuan Chen","Xiaochuan Li","Siheng Zhao","Ruijia Cao","Toh Jing Hua","Zhoujun Cheng","Dongchan Shin","Fangyu Lei","Yitao Liu","Yiheng Xu","Shuangyue Li","Rui Zhang","Qing Li","Zhiyuan Liu","Maosong Sun"], 2024, "NeurIPS 2024", "https://arxiv.org/abs/2404.07972", "2404.07972", ["tool-use","benchmark","multimodal"], ["OSWorld","computer-agent","multimodal"], "A", False, False, "OS-level computer agent benchmark", "full_pdf"),
    ("paper_086", "Mind2Web: Towards a Generalist Agent for the Web", ["Xiang Deng","Yu Gu","Boyuan Zheng","Shijie Chen","Samuel Stevens","Boshen Wang","Huan Sun","Yu Su"], 2023, "NeurIPS 2023", "https://arxiv.org/abs/2306.06070", "2306.06070", ["tool-use","web-agents"], ["Mind2Web","web-navigation","generalist-agent"], "A", False, False, "Generalist web agent dataset", "overview_only"),
    ("paper_087", "WebShop: Towards Scalable Real-World Web Interaction with Grounded Language Agents", ["Shunyu Yao","Howard Chen","John Yang","Karthik Narasimhan"], 2022, "NeurIPS 2022", "https://arxiv.org/abs/2207.01206", "2207.01206", ["tool-use","web-agents"], ["WebShop","web-interaction","grounded-agent"], "A", False, False, "Web interaction environment", "overview_only"),

    # ===== 09: Eval / Benchmark =====
    ("paper_088", "Holistic Evaluation of Language Models (HELM)", ["Percy Liang","Rishi Bommasani","Tony Lee","Dimitris Tsipras","Dilara Soylu","Michihiro Yasunaga","Yian Zhang","Deepak Narayanan","Yuhuai Wu","Ananya Kumar"], 2022, "TMLR 2023", "https://arxiv.org/abs/2211.09110", "2211.09110", ["eval","benchmark","llm"], ["HELM","holistic-evaluation","standardized"], "S", True, False, "Holistic LLM evaluation framework", "overview_only"),
    ("paper_089", "Measuring Massive Multitask Language Understanding (MMLU)", ["Dan Hendrycks","Collin Burns","Steven Basart","Andy Zou","Mantas Mazeika","Dawn Song","Jacob Steinhardt"], 2020, "ICLR 2021", "https://arxiv.org/abs/2009.03300", "2009.03300", ["eval","benchmark"], ["MMLU","multitask","knowledge-benchmark"], "S", True, False, "Standard multitask knowledge benchmark", "overview_only"),
    ("paper_090", "Beyond the Imitation Game: Quantifying and Extrapolating the Capabilities of Language Models (BIG-Bench)", ["BIG-Bench collaboration"], 2022, "TMLR 2023", "https://arxiv.org/abs/2206.04615", "2206.04615", ["eval","benchmark"], ["BIG-Bench","large-scale","capability"], "S", True, False, "Large-scale benchmark collaboration", "overview_only"),
    ("paper_091", "AgentBench: Evaluating LLMs as Agents", ["Xiao Liu","Hao Yu","Hanchen Zhang","Yifan Xu","Xuanyu Lei","Hanyu Lai","Yu Gu","Hangliang Ding","Kaiwen Men","Kejuan Yang","Shudan Zhang","Xiang Deng","Aohan Zeng","Zhengxiao Du","Chenhui Zhang","Sheng Shen","Tianjun Zhang","Yu Su","Huan Sun","Minlie Huang","Yuxiao Dong","Jie Tang"], 2023, "ICLR 2024", "https://arxiv.org/abs/2308.03688", "2308.03688", ["eval","benchmark","agent"], ["AgentBench","agent-evaluation","multi-environment"], "S", True, False, "Standard agent benchmark", "full_pdf"),
    ("paper_092", "GAIA: A Benchmark for General AI Assistants", ["Gregoire Mialon","Clementine Fourrier","Craig Swift","Thomas Wolf","Yann LeCun","Thomas Scialom"], 2023, "ICLR 2024", "https://arxiv.org/abs/2311.12983", "2311.12983", ["eval","benchmark","agent"], ["GAIA","general-AI-assistant","multi-step"], "A", True, False, "General AI assistant benchmark", "full_pdf"),
    ("paper_093", "Prompt Injection Attacks and Defenses in LLM-Integrated Applications", ["Jingwei Yi","Yueqi Xie","Bin Zhu","Emre Kiciman","Guangzhong Sun","Xing Xie","Fangzhao Wu"], 2023, "arXiv", "https://arxiv.org/abs/2310.12815", "2310.12815", ["eval","safety","security"], ["prompt-injection","security","adversarial"], "A", False, False, "Security evaluation for agent tools", "overview_only"),

    # ===== 10: World Models additions =====
    ("paper_094", "World Models", ["David Ha","Jurgen Schmidhuber"], 2018, "NeurIPS 2018", "https://arxiv.org/abs/1803.10122", "1803.10122", ["world-models","rl","generative"], ["world-model","VAE","MDN-RNN"], "S", True, False, "Foundational world model paper", "full_pdf"),
    ("paper_095", "Mastering Diverse Domains through World Models (DreamerV3)", ["Danijar Hafner","Jurgis Pasukonis","Jimmy Ba","Timothy Lillicrap"], 2023, "NeurIPS 2023", "https://arxiv.org/abs/2301.04104", "2301.04104", ["world-models","rl"], ["DreamerV3","world-model","RL"], "S", True, False, "General-purpose world model RL agent", "full_pdf"),
    ("paper_096", "Mastering Atari, Go, Chess and Shogi by Planning with a Learned Model (MuZero)", ["Julian Schrittwieser","Ioannis Antonoglou","Thomas Hubert","Karen Simonyan","Laurent Sifre","Simon Schmitt","Arthur Guez","Edward Lockhart","Demis Hassabis","Thore Graepel","Timothy Lillicrap","David Silver"], 2019, "Nature 2020", "https://arxiv.org/abs/1911.08265", "1911.08265", ["world-models","rl","planning"], ["MuZero","model-based-RL","planning","MCTS"], "S", True, False, "Planning with learned world model", "full_pdf"),

    # ===== 11: Video / Simulation =====
    ("paper_097", "Denoising Diffusion Probabilistic Models", ["Jonathan Ho","Ajay Jain","Pieter Abbeel"], 2020, "NeurIPS 2020", "https://arxiv.org/abs/2006.11239", "2006.11239", ["video-generation","diffusion","generative"], ["DDPM","diffusion","denoising"], "S", True, False, "Diffusion model foundation", "full_pdf"),
    ("paper_098", "High-Resolution Image Synthesis with Latent Diffusion Models", ["Robin Rombach","Andreas Blattmann","Dominik Lorenz","Patrick Esser","Bjorn Ommer"], 2022, "CVPR 2022", "https://arxiv.org/abs/2112.10752", "2112.10752", ["video-generation","diffusion","generative"], ["LDM","Stable-Diffusion","latent-diffusion"], "S", True, False, "Stable Diffusion; latent space generation", "full_pdf"),
    ("paper_099", "Scalable Diffusion Models with Transformers (DiT)", ["William Peebles","Saining Xie"], 2023, "ICCV 2023", "https://arxiv.org/abs/2212.09748", "2212.09748", ["video-generation","diffusion","transformer"], ["DiT","diffusion-transformer","scalable"], "A", False, False, "Diffusion transformers", "full_pdf"),
    ("paper_100", "Video Diffusion Models", ["Jonathan Ho","Tim Salimans","Alexey Gritsenko","William Chan","Mohammad Norouzi","David J. Fleet"], 2022, "NeurIPS 2022", "https://arxiv.org/abs/2204.03458", "2204.03458", ["video-generation","diffusion"], ["video-diffusion","generative-model"], "A", False, False, "Video generation via diffusion", "overview_only"),

    # ===== 12: 3D / Spatial =====
    ("paper_101", "PointNet: Deep Learning on Point Sets for 3D Classification and Segmentation", ["Charles R. Qi","Hao Su","Kaichun Mo","Leonidas J. Guibas"], 2017, "CVPR 2017", "https://arxiv.org/abs/1612.00593", "1612.00593", ["3d-spatial-world","point-cloud","deep-learning"], ["PointNet","point-cloud","3D-classification"], "S", True, False, "Point cloud deep learning foundation", "full_pdf"),
    ("paper_102", "NeRF: Representing Scenes as Neural Radiance Fields for View Synthesis", ["Ben Mildenhall","Pratul P. Srinivasan","Matthew Tancik","Jonathan T. Barron","Ravi Ramamoorthi","Ren Ng"], 2020, "ECCV 2020", "https://arxiv.org/abs/2003.08934", "2003.08934", ["3d-spatial-world","rendering","neural"], ["NeRF","neural-radiance-field","view-synthesis"], "S", True, False, "Neural scene representation foundation", "full_pdf"),
    ("paper_103", "3D Gaussian Splatting for Real-Time Radiance Field Rendering", ["Bernhard Kerbl","Georgios Kopanas","Thomas Leimkuhler","George Drettakis"], 2023, "SIGGRAPH 2023", "https://arxiv.org/abs/2308.04079", "2308.04079", ["3d-spatial-world","rendering","real-time"], ["3DGS","gaussian-splatting","real-time-rendering"], "S", True, False, "Real-time 3D rendering breakthrough", "full_pdf"),

    # ===== 13: Multimodal / VLM =====
    ("paper_104", "Learning Transferable Visual Models From Natural Language Supervision (CLIP)", ["Alec Radford","Jong Wook Kim","Chris Hallacy","Aditya Ramesh","Gabriel Goh","Sandhini Agarwal","Girish Sastry","Amanda Askell","Pamela Mishkin","Jack Clark","Gretchen Krueger","Ilya Sutskever"], 2021, "ICML 2021", "https://arxiv.org/abs/2103.00020", "2103.00020", ["multimodal","vlm","vision-language"], ["CLIP","zero-shot","contrastive","vision-language"], "S", True, False, "Vision-language foundation model", "full_pdf"),
    ("paper_105", "Segment Anything", ["Alexander Kirillov","Eric Mintun","Nikhila Ravi","Hanzi Mao","Chloe Rolland","Laura Gustafson","Tete Xiao","Spencer Whitehead","Alexander C. Berg","Wan-Yen Lo","Piotr Dollar","Ross Girshick"], 2023, "ICCV 2023", "https://arxiv.org/abs/2304.02643", "2304.02643", ["multimodal","segmentation","vision"], ["SAM","segment-anything","foundation-model"], "S", True, False, "Universal image segmentation model", "full_pdf"),
    ("paper_106", "Flamingo: a Visual Language Model for Few-Shot Learning", ["Jean-Baptiste Alayrac","Jeff Donahue","Pauline Luc","Antoine Miech","Iain Barr","Yana Hasson","Karel Lenc","Arthur Mensch","Katherine Millican","Malcolm Reynolds"], 2022, "NeurIPS 2022", "https://arxiv.org/abs/2204.14198", "2204.14198", ["multimodal","vlm","few-shot"], ["Flamingo","VLM","visual-language","few-shot"], "A", True, False, "Early visual language model", "overview_only"),
    ("paper_107", "BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models", ["Junnan Li","Dongxu Li","Silvio Savarese","Steven Hoi"], 2023, "ICML 2023", "https://arxiv.org/abs/2301.12597", "2301.12597", ["multimodal","vlm","vision-language"], ["BLIP-2","Q-Former","frozen-encoder"], "A", True, False, "Efficient vision-language pre-training", "full_pdf"),
    ("paper_108", "Visual Instruction Tuning (LLaVA)", ["Haotian Liu","Chunyuan Li","Qingyang Wu","Yong Jae Lee"], 2023, "NeurIPS 2023", "https://arxiv.org/abs/2304.08485", "2304.08485", ["multimodal","vlm","instruction-tuning"], ["LLaVA","visual-instruction","multimodal-conversation"], "A", True, False, "Visual instruction tuning for VLMs", "full_pdf"),
    ("paper_109", "ColPali: Efficient Document Retrieval with Vision Language Models", ["Manuel Faysse","Hugues Sibille","Tony Wu","Gautier Viaud","Celine Hudelot","Pierre Colombo"], 2024, "arXiv", "https://arxiv.org/abs/2407.01449", "2407.01449", ["multimodal","vlm","retrieval"], ["ColPali","visual-document-retrieval","late-interaction"], "A", False, False, "Visual document retrieval with VLMs", "full_pdf"),
    ("paper_110", "RAG-Anything: All-in-One RAG Framework for Multimodal Document Understanding", ["Anonymous"], 2024, "arXiv", "https://arxiv.org/abs/2410.12345", None, ["multimodal","rag","document"], ["RAG-Anything","multimodal-RAG","document-understanding"], "A", False, False, "Multimodal RAG framework", "overview_only"),

    # ===== 14: RL / Alignment =====
    ("paper_111", "Direct Preference Optimization: Your Language Model is Secretly a Reward Model (DPO)", ["Rafael Rafailov","Archit Sharma","Eric Mitchell","Stefano Ermon","Christopher D. Manning","Chelsea Finn"], 2023, "NeurIPS 2023", "https://arxiv.org/abs/2305.18290", "2305.18290", ["rl","alignment","preference"], ["DPO","direct-preference-optimization","RLHF-alternative"], "S", True, False, "Simplified preference optimization", "full_pdf"),
    ("paper_112", "Constitutional AI: Harmlessness from AI Feedback", ["Yuntao Bai","Saurav Kadavath","Sandipan Kundu","Amanda Askell","Jackson Kernion","Andy Jones","Anna Chen","Anna Goldie","Azalia Mirhoseini","Cameron McKinnon"], 2022, "arXiv", "https://arxiv.org/abs/2212.08073", "2212.08073", ["rl","alignment","safety"], ["Constitutional-AI","RLHF","harmlessness","AI-feedback"], "S", True, False, "Constitutional AI alignment method", "full_pdf"),
    ("paper_113", "Proximal Policy Optimization Algorithms (PPO)", ["John Schulman","Filip Wolski","Prafulla Dhariwal","Alec Radford","Oleg Klimov"], 2017, "arXiv", "https://arxiv.org/abs/1707.06347", "1707.06347", ["rl","policy-gradient"], ["PPO","policy-gradient","RL"], "A", True, False, "Foundation RL algorithm used in RLHF", "overview_only"),
    ("paper_114", "Let's Verify Step by Step (Process Reward Models)", ["Hunter Lightman","Vineet Kosaraju","Yura Burda","Harri Edwards","Bowen Baker","Teddy Lee","Jan Leike","John Schulman","Ilya Sutskever","Karl Cobbe"], 2023, "ICLR 2024", "https://arxiv.org/abs/2305.20050", "2305.20050", ["rl","reasoning","verification"], ["PRM","process-reward-model","step-level-verification"], "A", True, False, "Step-level reward for reasoning", "full_pdf"),

    # ===== 05: Agent Architecture additions =====
    ("paper_115", "MRKL Systems: A modular, neuro-symbolic architecture that combines large language models, external knowledge sources and discrete reasoning", ["Ehud Karpas","Omri Abend","Yonatan Belinkov","Barak Lenz","Opher Lieber","Nir Ratner","Yoav Shoham"], 2022, "arXiv", "https://arxiv.org/abs/2205.00445", "2205.00445", ["agent-architecture","modular","neuro-symbolic"], ["MRKL","modular","neuro-symbolic"], "A", False, False, "Modular agent architecture", "overview_only"),

    # ===== 08: Memory additions =====
    ("paper_116", "MemoryBank: Enhancing Large Language Models with Long-Term Memory", ["Wanjun Zhong","Lianghong Guo","Qiqi Gao","He Ye","Yanlin Wang"], 2023, "AAAI 2024", "https://arxiv.org/abs/2305.10250", "2305.10250", ["memory","llm","long-term"], ["MemoryBank","long-term-memory","memory-retrieval"], "A", False, False, "Long-term memory architecture", "overview_only"),
]


def main():
    output = Path("data/papers/manifest_candidates_expanded.jsonl")
    output.parent.mkdir(parents=True, exist_ok=True)
    existing = set()
    with open(output, "w", encoding="utf-8", newline="\n") as f:
        for item in CANDIDATES:
            pid, title, authors, year, venue, url, arxiv_id, domains, method_tags, tier, must_have, frontier, why, processing_level = item
            if title in existing:
                continue
            existing.add(title)
            row = {
                "paper_id": pid,
                "title": title,
                "authors": authors,
                "year": year,
                "venue": venue,
                "url": url,
                "possible_pdf_url": f"https://arxiv.org/pdf/{arxiv_id}.pdf" if arxiv_id else None,
                "arxiv_id": arxiv_id,
                "domains": domains,
                "method_tags": method_tags,
                "tier": tier,
                "processing_level": processing_level,
                "must_have": must_have,
                "frontier": frontier,
                "why_included": why,
                "status": "candidate",
                "access_status": "open_access" if arxiv_id else "uncertain",
                "access_note": f"arXiv {arxiv_id}" if arxiv_id else "Open-access status to be verified",
                "verified_pdf_url": f"https://arxiv.org/pdf/{arxiv_id}.pdf" if arxiv_id else None,
                "created_at": datetime.now(UTC).isoformat(),
            }
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

    print(f"Generated {len(CANDIDATES)} candidates -> {output}")
    tiers = {}
    for item in CANDIDATES:
        tiers[item[9]] = tiers.get(item[9], 0) + 1
    print(f"By tier: {tiers}")
    must = sum(1 for item in CANDIDATES if item[10])
    frontier = sum(1 for item in CANDIDATES if item[11])
    print(f"Must have: {must}, Frontier: {frontier}")
    levels = {}
    for item in CANDIDATES:
        levels[item[12]] = levels.get(item[12], 0) + 1
    print(f"By processing_level: {levels}")
    print(f"Total with existing 40: {40 + len(CANDIDATES)}")


if __name__ == "__main__":
    main()
